#此工作流程使用了未经GitHub认证的操作。
#它们由第三方提供，并受
#单独的服务条款、隐私政策和支持
#文档。
#此工作流将使用Gradle构建一个Java项目，并缓存/恢复任何依赖项，以缩短工作流执行时间
#有关更多信息，请参见:https://docs . github . com/en/actions/automating-build-and-tests/build-and-testing-Java-with-gradle

名字: 带Gradle的Java CI

在:
推:
分支: [ "主要" ]
拉取请求:
分支: [ "主要" ]

工作:
建设:

连续运行: Ubuntu-最新版
许可:
内容: 阅读

步伐:
    - 使用: 动作/签出@v4
    - 名字: 建立JDK 17号
使用: 操作/设置-java@v4
随着:
java版本: '17'
分布: 特穆林

    #配置Gradle以优化GitHub操作的使用，包括缓存下载的依赖项。
    #请参阅:https://github . com/gradle/actions/blob/main/setup-gradle/readme . MD
    - 名字: 设置梯度
使用: gradle/actions/setup-gradle @ af1da 67850 ed 9 a4 cedd 57 bfd 976089 DD 991 e 2582# 4 . 0 . 0版

    - 名字: 用Gradle包装器构建
      run: ./gradlew build

    # NOTE: The Gradle Wrapper is the default and recommended way to run Gradle (https://docs.gradle.org/current/userguide/gradle_wrapper.html).
    # If your project does not have the Gradle Wrapper configured, you can use the following configuration to run Gradle with a specified version.
    #
    # - name: Setup Gradle
    #   uses: gradle/actions/setup-gradle@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
    #   with:
    #     gradle-version: '8.9'
    #
    # - name: Build with Gradle 8.9
    #   run: gradle build

  dependency-submission:

    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    # Generates and submits a dependency graph, enabling Dependabot Alerts for all project dependencies.
    # See: https://github.com/gradle/actions/blob/main/dependency-submission/README.md
    - name: Generate and submit dependency graph
      uses: gradle/actions/dependency-submission@af1da67850ed9a4cedd57bfd976089dd991e2582 # v4.0.0
